# -*- coding: utf-8 -*-
"""CatBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vs5DZhV7UdOqSShMi8hscx415cB0pj-y
"""

#Katagorik değişkenler ile otomatik olarak mücadele edebilen GBM türevi

!pip install catboost
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV, cross_validate, RandomizedSearchCV, validation_curve
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
warnings.simplefilter(action='ignore', category=Warning)

df = pd.read_csv("/content/drive/MyDrive/Datasets/diabetes.csv")

y = df["Outcome"]
X = df.drop(["Outcome"], axis=1)



catboost_model = CatBoostClassifier(random_state=17, verbose=False)

cv_result = cross_validate(catboost_model, X, y, cv=10, scoring=["accuracy", "f1", "roc_auc"])
print(cv_result['test_accuracy'].mean())
print(cv_result['test_f1'].mean())
print(cv_result['test_roc_auc'].mean())

catboost_model.get_params()

catboost_params = {
    'iterations': [200, 300, 500, 1000],
    'learning_rate': [0.01, 0.1],
    'depth': [3, 5, 8]
}

catboost_best_grid = GridSearchCV(catboost_model, catboost_params, cv=10, n_jobs=-1, verbose=True).fit(X, y)

catboost_best_grid.best_params_

catboost_final = catboost_model.set_params(**catboost_best_grid.best_params_, random_state=17, verbose=False).fit(X, y)

cv_result = cross_validate(catboost_final, X, y, cv=5, scoring=["accuracy", "f1", "roc_auc"])
print(cv_result['test_accuracy'].mean())
print(cv_result['test_f1'].mean())
print(cv_result['test_roc_auc'].mean())

#Feature İmportance Visualization

def plot_importance(model, features, num=len(X), save=False) :
    feature_imp = pd.DataFrame ( {'Value' : model.feature_importances_, 'Feature' : features.columns})
    plt.figure(figsize=(10, 10))
    sns.set(font_scale=1)
    sns.barplot(x="Value", y="Feature", data=feature_imp.sort_values(by="Value",
                                                                    ascending=False) [0: num])
    plt.title ( 'Features' )
    plt.tight_layout ()
    plt.show ()
    if save:
        plt.savefig('importances.png')

plot_importance(catboost_final, X)